In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [ ]:
X, y = load_iris(return_X_y=True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[-1.13996673, -0.09410715, -1.36470113, -1.34681428],
       [ 0.70530315,  0.14616643,  1.00283398,  0.82073259],
       [-0.52487677,  0.86698719, -1.19146686, -1.34681428],
       [-0.89393074,  1.58780795, -1.30695637, -1.07587092],
       [-1.26298472,  0.86698719, -1.07597734, -1.34681428],
       [ 1.19737512, -0.57465433,  0.59862067,  0.27884587],
       [-1.38600271,  0.38644002, -1.24921162, -1.34681428],
       [ 1.93548308, -0.57465433,  1.34930253,  0.95620427],
       [-0.27884078, -0.09410715,  0.19440735,  0.14337419],
       [ 0.95133914, -0.33438074,  0.48313115,  0.14337419],
       [ 0.45926717,  0.86698719,  0.94508922,  1.49809099],
       [-1.26298472,  0.14616643, -1.24921162, -1.34681428],
       [ 0.58228516, -1.77602226,  0.36764163,  0.14337419],
       [-1.75505669,  0.38644002, -1.42244589, -1.34681428],
       [ 0.21323119, -2.01629585,  0.1366626 , -0.26304084],
       [-0.64789476,  1.58780795, -1.30695637, -1.34681428],
       [-0.0328048 , -0.

In [ ]:
(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[-1.13996673, -0.09410715, -1.36470113, -1.34681428],
       [ 0.70530315,  0.14616643,  1.00283398,  0.82073259],
       [-0.52487677,  0.86698719, -1.19146686, -1.34681428],
       [-0.89393074,  1.58780795, -1.30695637, -1.07587092],
       [-1.26298472,  0.86698719, -1.07597734, -1.34681428],
       [ 1.19737512, -0.57465433,  0.59862067,  0.27884587],
       [-1.38600271,  0.38644002, -1.24921162, -1.34681428],
       [ 1.93548308, -0.57465433,  1.34930253,  0.95620427],
       [-0.27884078, -0.09410715,  0.19440735,  0.14337419],
       [ 0.95133914, -0.33438074,  0.48313115,  0.14337419],
       [ 0.45926717,  0.86698719,  0.94508922,  1.49809099],
       [-1.26298472,  0.14616643, -1.24921162, -1.34681428],
       [ 0.58228516, -1.77602226,  0.36764163,  0.14337419],
       [-1.75505669,  0.38644002, -1.42244589, -1.34681428],
       [ 0.21323119, -2.01629585,  0.1366626 , -0.26304084],
       [-0.64789476,  1.58780795, -1.30695637, -1.34681428],
       [-0.0328048 , -0.

In [ ]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[0.16666667, 0.36363636, 0.07017544, 0.04166667],
       [0.58333333, 0.40909091, 0.78947368, 0.70833333],
       [0.30555556, 0.54545455, 0.12280702, 0.04166667],
       [0.22222222, 0.68181818, 0.0877193 , 0.125     ],
       [0.13888889, 0.54545455, 0.15789474, 0.04166667],
       [0.69444444, 0.27272727, 0.66666667, 0.54166667],
       [0.11111111, 0.45454545, 0.10526316, 0.04166667],
       [0.86111111, 0.27272727, 0.89473684, 0.75      ],
       [0.36111111, 0.36363636, 0.54385965, 0.5       ],
       [0.63888889, 0.31818182, 0.63157895, 0.5       ],
       [0.52777778, 0.54545455, 0.77192982, 0.91666667],
       [0.13888889, 0.40909091, 0.10526316, 0.04166667],
       [0.55555556, 0.04545455, 0.59649123, 0.5       ],
       [0.02777778, 0.45454545, 0.05263158, 0.04166667],
       [0.47222222, 0.        , 0.52631579, 0.375     ],
       [0.27777778, 0.68181818, 0.0877193 , 0.04166667],
       [0.41666667, 0.22727273, 0.54385965, 0.375     ],
       [0.36111111, 0.22727273,

In [ ]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.16666667, 0.36363636, 0.07017544, 0.04166667],
       [0.58333333, 0.40909091, 0.78947368, 0.70833333],
       [0.30555556, 0.54545455, 0.12280702, 0.04166667],
       [0.22222222, 0.68181818, 0.0877193 , 0.125     ],
       [0.13888889, 0.54545455, 0.15789474, 0.04166667],
       [0.69444444, 0.27272727, 0.66666667, 0.54166667],
       [0.11111111, 0.45454545, 0.10526316, 0.04166667],
       [0.86111111, 0.27272727, 0.89473684, 0.75      ],
       [0.36111111, 0.36363636, 0.54385965, 0.5       ],
       [0.63888889, 0.31818182, 0.63157895, 0.5       ],
       [0.52777778, 0.54545455, 0.77192982, 0.91666667],
       [0.13888889, 0.40909091, 0.10526316, 0.04166667],
       [0.55555556, 0.04545455, 0.59649123, 0.5       ],
       [0.02777778, 0.45454545, 0.05263158, 0.04166667],
       [0.47222222, 0.        , 0.52631579, 0.375     ],
       [0.27777778, 0.68181818, 0.0877193 , 0.04166667],
       [0.41666667, 0.22727273, 0.54385965, 0.375     ],
       [0.36111111, 0.22727273,